// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hashdb.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultCode_Code int32

const (
	ResultCode_CODE_UNSPECIFIED           ResultCode_Code = 0
	ResultCode_CODE_SUCCESS               ResultCode_Code = 1
	ResultCode_CODE_DB_KEY_NOT_FOUND      ResultCode_Code = 2
	ResultCode_CODE_DB_ERROR              ResultCode_Code = 3
	ResultCode_CODE_INTERNAL_ERROR        ResultCode_Code = 4
	ResultCode_CODE_SMT_INVALID_DATA_SIZE ResultCode_Code = 14
)

var ResultCode_Code_name = map[int32]string{
	0:  "CODE_UNSPECIFIED",
	1:  "CODE_SUCCESS",
	2:  "CODE_DB_KEY_NOT_FOUND",
	3:  "CODE_DB_ERROR",
	4:  "CODE_INTERNAL_ERROR",
	14: "CODE_SMT_INVALID_DATA_SIZE",
}

var ResultCode_Code_value = map[string]int32{
	"CODE_UNSPECIFIED":           0,
	"CODE_SUCCESS":               1,
	"CODE_DB_KEY_NOT_FOUND":      2,
	"CODE_DB_ERROR":              3,
	"CODE_INTERNAL_ERROR":        4,
	"CODE_SMT_INVALID_DATA_SIZE": 14,
}

func (x ResultCode_Code) String() string {
	return proto.EnumName(ResultCode_Code_name, int32(x))
}

func (ResultCode_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{19, 0}
}

type Version struct {
	V0_0_1               string   `protobuf:"bytes,1,opt,name=v0_0_1,json=v001,proto3" json:"v0_0_1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{0}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetV0_0_1() string {
	if m != nil {
		return m.V0_0_1
	}
	return ""
}

//*
// @dev SetRequest
// @param {old_root} - merkle-tree root
// @param {key} - key to set
// @param {value} - scalar value to set (HEX string format)
// @param {persistent} - indicates if it should be stored in the SQL database (true) or only in the memory cache (false)
// @param {details} - indicates if it should return all response parameters (true) or just the new root (false)
// @param {get_db_read_log} - indicates if it should return the DB reads generated during the execution of the request
type SetRequest struct {
	OldRoot              *Fea     `protobuf:"bytes,1,opt,name=old_root,json=oldRoot,proto3" json:"old_root,omitempty"`
	Key                  *Fea     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Persistent           bool     `protobuf:"varint,4,opt,name=persistent,proto3" json:"persistent,omitempty"`
	Details              bool     `protobuf:"varint,5,opt,name=details,proto3" json:"details,omitempty"`
	GetDbReadLog         bool     `protobuf:"varint,6,opt,name=get_db_read_log,json=getDbReadLog,proto3" json:"get_db_read_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{1}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetOldRoot() *Fea {
	if m != nil {
		return m.OldRoot
	}
	return nil
}

func (m *SetRequest) GetKey() *Fea {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SetRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SetRequest) GetPersistent() bool {
	if m != nil {
		return m.Persistent
	}
	return false
}

func (m *SetRequest) GetDetails() bool {
	if m != nil {
		return m.Details
	}
	return false
}

func (m *SetRequest) GetGetDbReadLog() bool {
	if m != nil {
		return m.GetDbReadLog
	}
	return false
}

//*
// @dev GetRequest
// @param {root} - merkle-tree root
// @param {key} - key to look for
// @param {details} - indicates if it should return all response parameters (true) or just the new root (false)
// @param {get_db_read_log} - indicates if it should return the DB reads generated during the execution of the request
type GetRequest struct {
	Root                 *Fea     `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Key                  *Fea     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Details              bool     `protobuf:"varint,3,opt,name=details,proto3" json:"details,omitempty"`
	GetDbReadLog         bool     `protobuf:"varint,4,opt,name=get_db_read_log,json=getDbReadLog,proto3" json:"get_db_read_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetRoot() *Fea {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *GetRequest) GetKey() *Fea {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetRequest) GetDetails() bool {
	if m != nil {
		return m.Details
	}
	return false
}

func (m *GetRequest) GetGetDbReadLog() bool {
	if m != nil {
		return m.GetDbReadLog
	}
	return false
}

//*
// @dev SetProgramRequest
// @param {key} - key to set
// @param {data} - Program data to store
// @param {persistent} - indicates if it should be stored in the SQL database (true) or only in the memory cache (false)
type SetProgramRequest struct {
	Key                  *Fea     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Persistent           bool     `protobuf:"varint,3,opt,name=persistent,proto3" json:"persistent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetProgramRequest) Reset()         { *m = SetProgramRequest{} }
func (m *SetProgramRequest) String() string { return proto.CompactTextString(m) }
func (*SetProgramRequest) ProtoMessage()    {}
func (*SetProgramRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{3}
}

func (m *SetProgramRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetProgramRequest.Unmarshal(m, b)
}
func (m *SetProgramRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetProgramRequest.Marshal(b, m, deterministic)
}
func (m *SetProgramRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetProgramRequest.Merge(m, src)
}
func (m *SetProgramRequest) XXX_Size() int {
	return xxx_messageInfo_SetProgramRequest.Size(m)
}
func (m *SetProgramRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetProgramRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetProgramRequest proto.InternalMessageInfo

func (m *SetProgramRequest) GetKey() *Fea {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SetProgramRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SetProgramRequest) GetPersistent() bool {
	if m != nil {
		return m.Persistent
	}
	return false
}

//*
// @dev GetProgramRequest
// @param {key} - key to get program data
type GetProgramRequest struct {
	Key                  *Fea     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProgramRequest) Reset()         { *m = GetProgramRequest{} }
func (m *GetProgramRequest) String() string { return proto.CompactTextString(m) }
func (*GetProgramRequest) ProtoMessage()    {}
func (*GetProgramRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{4}
}

func (m *GetProgramRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProgramRequest.Unmarshal(m, b)
}
func (m *GetProgramRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProgramRequest.Marshal(b, m, deterministic)
}
func (m *GetProgramRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProgramRequest.Merge(m, src)
}
func (m *GetProgramRequest) XXX_Size() int {
	return xxx_messageInfo_GetProgramRequest.Size(m)
}
func (m *GetProgramRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProgramRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProgramRequest proto.InternalMessageInfo

func (m *GetProgramRequest) GetKey() *Fea {
	if m != nil {
		return m.Key
	}
	return nil
}

//*
// @dev LoadDBRequest
// @param {input_db} - list of db records (MT) to load in the database
// @param {persistent} - indicates if it should be stored in the SQL database (true) or only in the memory cache (false)
type LoadDBRequest struct {
	InputDb              map[string]*FeList `protobuf:"bytes,1,rep,name=input_db,json=inputDb,proto3" json:"input_db,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Persistent           bool               `protobuf:"varint,2,opt,name=persistent,proto3" json:"persistent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LoadDBRequest) Reset()         { *m = LoadDBRequest{} }
func (m *LoadDBRequest) String() string { return proto.CompactTextString(m) }
func (*LoadDBRequest) ProtoMessage()    {}
func (*LoadDBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{5}
}

func (m *LoadDBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadDBRequest.Unmarshal(m, b)
}
func (m *LoadDBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadDBRequest.Marshal(b, m, deterministic)
}
func (m *LoadDBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadDBRequest.Merge(m, src)
}
func (m *LoadDBRequest) XXX_Size() int {
	return xxx_messageInfo_LoadDBRequest.Size(m)
}
func (m *LoadDBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadDBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadDBRequest proto.InternalMessageInfo

func (m *LoadDBRequest) GetInputDb() map[string]*FeList {
	if m != nil {
		return m.InputDb
	}
	return nil
}

func (m *LoadDBRequest) GetPersistent() bool {
	if m != nil {
		return m.Persistent
	}
	return false
}

//*
// @dev LoadProgramDBRequest
// @param {input_program_db} - list of db records (program) to load in the database
// @param {persistent} - indicates if it should be stored in the SQL database (true) or only in the memory cache (false)
type LoadProgramDBRequest struct {
	InputProgramDb       map[string][]byte `protobuf:"bytes,1,rep,name=input_program_db,json=inputProgramDb,proto3" json:"input_program_db,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Persistent           bool              `protobuf:"varint,2,opt,name=persistent,proto3" json:"persistent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LoadProgramDBRequest) Reset()         { *m = LoadProgramDBRequest{} }
func (m *LoadProgramDBRequest) String() string { return proto.CompactTextString(m) }
func (*LoadProgramDBRequest) ProtoMessage()    {}
func (*LoadProgramDBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{6}
}

func (m *LoadProgramDBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadProgramDBRequest.Unmarshal(m, b)
}
func (m *LoadProgramDBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadProgramDBRequest.Marshal(b, m, deterministic)
}
func (m *LoadProgramDBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadProgramDBRequest.Merge(m, src)
}
func (m *LoadProgramDBRequest) XXX_Size() int {
	return xxx_messageInfo_LoadProgramDBRequest.Size(m)
}
func (m *LoadProgramDBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadProgramDBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadProgramDBRequest proto.InternalMessageInfo

func (m *LoadProgramDBRequest) GetInputProgramDb() map[string][]byte {
	if m != nil {
		return m.InputProgramDb
	}
	return nil
}

func (m *LoadProgramDBRequest) GetPersistent() bool {
	if m != nil {
		return m.Persistent
	}
	return false
}

//*
// @dev GetFlushDataRequest
// @param {flush_id} - last stored flush ID got using this method, or 0 if it never was called before
type GetFlushDataRequest struct {
	FlushId              uint64   `protobuf:"varint,1,opt,name=flush_id,json=flushId,proto3" json:"flush_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlushDataRequest) Reset()         { *m = GetFlushDataRequest{} }
func (m *GetFlushDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetFlushDataRequest) ProtoMessage()    {}
func (*GetFlushDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{7}
}

func (m *GetFlushDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlushDataRequest.Unmarshal(m, b)
}
func (m *GetFlushDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlushDataRequest.Marshal(b, m, deterministic)
}
func (m *GetFlushDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlushDataRequest.Merge(m, src)
}
func (m *GetFlushDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetFlushDataRequest.Size(m)
}
func (m *GetFlushDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlushDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlushDataRequest proto.InternalMessageInfo

func (m *GetFlushDataRequest) GetFlushId() uint64 {
	if m != nil {
		return m.FlushId
	}
	return 0
}

//*
// @dev SetResponse
// @param {old_root} - merkle-tree root
// @param {new_root} - merkle-tree new root
// @param {key} - key to look for
// @param {siblings} - array of siblings
// @param {ins_key} - key found
// @param {ins_value} - value found (HEX string format)
// @param {is_old0} - is new insert or delete
// @param {old_value} - old value (HEX string format)
// @param {new_value} - new value (HEX string format)
// @param {mode}
// @param {proof_hash_counter}
// @param {db_read_log} - list of db records read during the execution of the request
// @param {result} - result code
type SetResponse struct {
	OldRoot              *Fea                    `protobuf:"bytes,1,opt,name=old_root,json=oldRoot,proto3" json:"old_root,omitempty"`
	NewRoot              *Fea                    `protobuf:"bytes,2,opt,name=new_root,json=newRoot,proto3" json:"new_root,omitempty"`
	Key                  *Fea                    `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Siblings             map[uint64]*SiblingList `protobuf:"bytes,4,rep,name=siblings,proto3" json:"siblings,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	InsKey               *Fea                    `protobuf:"bytes,5,opt,name=ins_key,json=insKey,proto3" json:"ins_key,omitempty"`
	InsValue             string                  `protobuf:"bytes,6,opt,name=ins_value,json=insValue,proto3" json:"ins_value,omitempty"`
	IsOld0               bool                    `protobuf:"varint,7,opt,name=is_old0,json=isOld0,proto3" json:"is_old0,omitempty"`
	OldValue             string                  `protobuf:"bytes,8,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             string                  `protobuf:"bytes,9,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	Mode                 string                  `protobuf:"bytes,10,opt,name=mode,proto3" json:"mode,omitempty"`
	ProofHashCounter     uint64                  `protobuf:"varint,11,opt,name=proof_hash_counter,json=proofHashCounter,proto3" json:"proof_hash_counter,omitempty"`
	DbReadLog            map[string]*FeList      `protobuf:"bytes,12,rep,name=db_read_log,json=dbReadLog,proto3" json:"db_read_log,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Result               *ResultCode             `protobuf:"bytes,13,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{8}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

func (m *SetResponse) GetOldRoot() *Fea {
	if m != nil {
		return m.OldRoot
	}
	return nil
}

func (m *SetResponse) GetNewRoot() *Fea {
	if m != nil {
		return m.NewRoot
	}
	return nil
}

func (m *SetResponse) GetKey() *Fea {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SetResponse) GetSiblings() map[uint64]*SiblingList {
	if m != nil {
		return m.Siblings
	}
	return nil
}

func (m *SetResponse) GetInsKey() *Fea {
	if m != nil {
		return m.InsKey
	}
	return nil
}

func (m *SetResponse) GetInsValue() string {
	if m != nil {
		return m.InsValue
	}
	return ""
}

func (m *SetResponse) GetIsOld0() bool {
	if m != nil {
		return m.IsOld0
	}
	return false
}

func (m *SetResponse) GetOldValue() string {
	if m != nil {
		return m.OldValue
	}
	return ""
}

func (m *SetResponse) GetNewValue() string {
	if m != nil {
		return m.NewValue
	}
	return ""
}

func (m *SetResponse) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *SetResponse) GetProofHashCounter() uint64 {
	if m != nil {
		return m.ProofHashCounter
	}
	return 0
}

func (m *SetResponse) GetDbReadLog() map[string]*FeList {
	if m != nil {
		return m.DbReadLog
	}
	return nil
}

func (m *SetResponse) GetResult() *ResultCode {
	if m != nil {
		return m.Result
	}
	return nil
}

//*
// @dev GetResponse
// @param {root} - merkle-tree root
// @param {key} - key to look for
// @param {siblings} - array of siblings
// @param {ins_key} - key found
// @param {ins_value} - value found (HEX string format)
// @param {is_old0} - is new insert or delete
// @param {value} - value retrieved (HEX string format)
// @param {proof_hash_counter}
// @param {db_read_log} - list of db records read during the execution of the request
// @param {result} - result code
type GetResponse struct {
	Root                 *Fea                    `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Key                  *Fea                    `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Siblings             map[uint64]*SiblingList `protobuf:"bytes,3,rep,name=siblings,proto3" json:"siblings,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	InsKey               *Fea                    `protobuf:"bytes,4,opt,name=ins_key,json=insKey,proto3" json:"ins_key,omitempty"`
	InsValue             string                  `protobuf:"bytes,5,opt,name=ins_value,json=insValue,proto3" json:"ins_value,omitempty"`
	IsOld0               bool                    `protobuf:"varint,6,opt,name=is_old0,json=isOld0,proto3" json:"is_old0,omitempty"`
	Value                string                  `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	ProofHashCounter     uint64                  `protobuf:"varint,8,opt,name=proof_hash_counter,json=proofHashCounter,proto3" json:"proof_hash_counter,omitempty"`
	DbReadLog            map[string]*FeList      `protobuf:"bytes,9,rep,name=db_read_log,json=dbReadLog,proto3" json:"db_read_log,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Result               *ResultCode             `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{9}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetRoot() *Fea {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *GetResponse) GetKey() *Fea {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetResponse) GetSiblings() map[uint64]*SiblingList {
	if m != nil {
		return m.Siblings
	}
	return nil
}

func (m *GetResponse) GetInsKey() *Fea {
	if m != nil {
		return m.InsKey
	}
	return nil
}

func (m *GetResponse) GetInsValue() string {
	if m != nil {
		return m.InsValue
	}
	return ""
}

func (m *GetResponse) GetIsOld0() bool {
	if m != nil {
		return m.IsOld0
	}
	return false
}

func (m *GetResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GetResponse) GetProofHashCounter() uint64 {
	if m != nil {
		return m.ProofHashCounter
	}
	return 0
}

func (m *GetResponse) GetDbReadLog() map[string]*FeList {
	if m != nil {
		return m.DbReadLog
	}
	return nil
}

func (m *GetResponse) GetResult() *ResultCode {
	if m != nil {
		return m.Result
	}
	return nil
}

//*
// @dev SetProgramResponse
// @param {result} - result code
type SetProgramResponse struct {
	Result               *ResultCode `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetProgramResponse) Reset()         { *m = SetProgramResponse{} }
func (m *SetProgramResponse) String() string { return proto.CompactTextString(m) }
func (*SetProgramResponse) ProtoMessage()    {}
func (*SetProgramResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{10}
}

func (m *SetProgramResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetProgramResponse.Unmarshal(m, b)
}
func (m *SetProgramResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetProgramResponse.Marshal(b, m, deterministic)
}
func (m *SetProgramResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetProgramResponse.Merge(m, src)
}
func (m *SetProgramResponse) XXX_Size() int {
	return xxx_messageInfo_SetProgramResponse.Size(m)
}
func (m *SetProgramResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetProgramResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetProgramResponse proto.InternalMessageInfo

func (m *SetProgramResponse) GetResult() *ResultCode {
	if m != nil {
		return m.Result
	}
	return nil
}

//*
// @dev GetProgramResponse
// @param {data} - program data retrieved
// @param {result} - result code
type GetProgramResponse struct {
	Data                 []byte      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Result               *ResultCode `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetProgramResponse) Reset()         { *m = GetProgramResponse{} }
func (m *GetProgramResponse) String() string { return proto.CompactTextString(m) }
func (*GetProgramResponse) ProtoMessage()    {}
func (*GetProgramResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{11}
}

func (m *GetProgramResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProgramResponse.Unmarshal(m, b)
}
func (m *GetProgramResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProgramResponse.Marshal(b, m, deterministic)
}
func (m *GetProgramResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProgramResponse.Merge(m, src)
}
func (m *GetProgramResponse) XXX_Size() int {
	return xxx_messageInfo_GetProgramResponse.Size(m)
}
func (m *GetProgramResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProgramResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProgramResponse proto.InternalMessageInfo

func (m *GetProgramResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetProgramResponse) GetResult() *ResultCode {
	if m != nil {
		return m.Result
	}
	return nil
}

//*
// @dev FlushResponse
// @param {flush_id} - id assigned to this flush data
// @param {stored_flush_id} - id of the last flush data sent to database
// @param {result} - result code
type FlushResponse struct {
	FlushId              uint64      `protobuf:"varint,1,opt,name=flush_id,json=flushId,proto3" json:"flush_id,omitempty"`
	StoredFlushId        uint64      `protobuf:"varint,2,opt,name=stored_flush_id,json=storedFlushId,proto3" json:"stored_flush_id,omitempty"`
	Result               *ResultCode `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FlushResponse) Reset()         { *m = FlushResponse{} }
func (m *FlushResponse) String() string { return proto.CompactTextString(m) }
func (*FlushResponse) ProtoMessage()    {}
func (*FlushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{12}
}

func (m *FlushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlushResponse.Unmarshal(m, b)
}
func (m *FlushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlushResponse.Marshal(b, m, deterministic)
}
func (m *FlushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlushResponse.Merge(m, src)
}
func (m *FlushResponse) XXX_Size() int {
	return xxx_messageInfo_FlushResponse.Size(m)
}
func (m *FlushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FlushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FlushResponse proto.InternalMessageInfo

func (m *FlushResponse) GetFlushId() uint64 {
	if m != nil {
		return m.FlushId
	}
	return 0
}

func (m *FlushResponse) GetStoredFlushId() uint64 {
	if m != nil {
		return m.StoredFlushId
	}
	return 0
}

func (m *FlushResponse) GetResult() *ResultCode {
	if m != nil {
		return m.Result
	}
	return nil
}

//*
// @dev GetFlushStatusResponse
// @param {stored_flush_id} - id of the last flush data sent to database
// @param {sending_flush_id} - id of the flush data being sent now to database
// @param {last_flush_id} - id assigned to the last call to flush
// @param {pending_to_flush_nodes} - number of SMT nodes pending to flush
// @param {pending_to_flush_program} - number of SC programs pending to flush
// @param {storing_nodes} - number of SMT nodes being stored in the hash database
// @param {storing_program} - number of SC programs being stored in the hash database
// @param {prover_id} - id assigned to this instance of the prover process
type GetFlushStatusResponse struct {
	StoredFlushId         uint64   `protobuf:"varint,1,opt,name=stored_flush_id,json=storedFlushId,proto3" json:"stored_flush_id,omitempty"`
	StoringFlushId        uint64   `protobuf:"varint,2,opt,name=storing_flush_id,json=storingFlushId,proto3" json:"storing_flush_id,omitempty"`
	LastFlushId           uint64   `protobuf:"varint,3,opt,name=last_flush_id,json=lastFlushId,proto3" json:"last_flush_id,omitempty"`
	PendingToFlushNodes   uint64   `protobuf:"varint,4,opt,name=pending_to_flush_nodes,json=pendingToFlushNodes,proto3" json:"pending_to_flush_nodes,omitempty"`
	PendingToFlushProgram uint64   `protobuf:"varint,5,opt,name=pending_to_flush_program,json=pendingToFlushProgram,proto3" json:"pending_to_flush_program,omitempty"`
	StoringNodes          uint64   `protobuf:"varint,6,opt,name=storing_nodes,json=storingNodes,proto3" json:"storing_nodes,omitempty"`
	StoringProgram        uint64   `protobuf:"varint,7,opt,name=storing_program,json=storingProgram,proto3" json:"storing_program,omitempty"`
	ProverId              string   `protobuf:"bytes,8,opt,name=prover_id,json=proverId,proto3" json:"prover_id,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *GetFlushStatusResponse) Reset()         { *m = GetFlushStatusResponse{} }
func (m *GetFlushStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetFlushStatusResponse) ProtoMessage()    {}
func (*GetFlushStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{13}
}

func (m *GetFlushStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlushStatusResponse.Unmarshal(m, b)
}
func (m *GetFlushStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlushStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetFlushStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlushStatusResponse.Merge(m, src)
}
func (m *GetFlushStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetFlushStatusResponse.Size(m)
}
func (m *GetFlushStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlushStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlushStatusResponse proto.InternalMessageInfo

func (m *GetFlushStatusResponse) GetStoredFlushId() uint64 {
	if m != nil {
		return m.StoredFlushId
	}
	return 0
}

func (m *GetFlushStatusResponse) GetStoringFlushId() uint64 {
	if m != nil {
		return m.StoringFlushId
	}
	return 0
}

func (m *GetFlushStatusResponse) GetLastFlushId() uint64 {
	if m != nil {
		return m.LastFlushId
	}
	return 0
}

func (m *GetFlushStatusResponse) GetPendingToFlushNodes() uint64 {
	if m != nil {
		return m.PendingToFlushNodes
	}
	return 0
}

func (m *GetFlushStatusResponse) GetPendingToFlushProgram() uint64 {
	if m != nil {
		return m.PendingToFlushProgram
	}
	return 0
}

func (m *GetFlushStatusResponse) GetStoringNodes() uint64 {
	if m != nil {
		return m.StoringNodes
	}
	return 0
}

func (m *GetFlushStatusResponse) GetStoringProgram() uint64 {
	if m != nil {
		return m.StoringProgram
	}
	return 0
}

func (m *GetFlushStatusResponse) GetProverId() string {
	if m != nil {
		return m.ProverId
	}
	return ""
}

//*
// @dev GetFlushDataResponse
// @param {stored_flush_id} - id of the last flush data sent to database
// @param {nodes} - data to insert in the nodes table
// @param {nodes_update} - data to update in the nodes table
// @param {program} - data to insert in the program table
// @param {program_update} - data to update in the program table
// @param {nodes_state_root} - nodes state root to update in the nodes table
// @param {result} - result code
type GetFlushDataResponse struct {
	StoredFlushId        uint64       `protobuf:"varint,1,opt,name=stored_flush_id,json=storedFlushId,proto3" json:"stored_flush_id,omitempty"`
	Nodes                []*FlushData `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	NodesUpdate          []*FlushData `protobuf:"bytes,3,rep,name=nodes_update,json=nodesUpdate,proto3" json:"nodes_update,omitempty"`
	Program              []*FlushData `protobuf:"bytes,4,rep,name=program,proto3" json:"program,omitempty"`
	ProgramUpdate        []*FlushData `protobuf:"bytes,5,rep,name=program_update,json=programUpdate,proto3" json:"program_update,omitempty"`
	NodesStateRoot       string       `protobuf:"bytes,6,opt,name=nodes_state_root,json=nodesStateRoot,proto3" json:"nodes_state_root,omitempty"`
	Result               *ResultCode  `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetFlushDataResponse) Reset()         { *m = GetFlushDataResponse{} }
func (m *GetFlushDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetFlushDataResponse) ProtoMessage()    {}
func (*GetFlushDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{14}
}

func (m *GetFlushDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlushDataResponse.Unmarshal(m, b)
}
func (m *GetFlushDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlushDataResponse.Marshal(b, m, deterministic)
}
func (m *GetFlushDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlushDataResponse.Merge(m, src)
}
func (m *GetFlushDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetFlushDataResponse.Size(m)
}
func (m *GetFlushDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlushDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlushDataResponse proto.InternalMessageInfo

func (m *GetFlushDataResponse) GetStoredFlushId() uint64 {
	if m != nil {
		return m.StoredFlushId
	}
	return 0
}

func (m *GetFlushDataResponse) GetNodes() []*FlushData {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *GetFlushDataResponse) GetNodesUpdate() []*FlushData {
	if m != nil {
		return m.NodesUpdate
	}
	return nil
}

func (m *GetFlushDataResponse) GetProgram() []*FlushData {
	if m != nil {
		return m.Program
	}
	return nil
}

func (m *GetFlushDataResponse) GetProgramUpdate() []*FlushData {
	if m != nil {
		return m.ProgramUpdate
	}
	return nil
}

func (m *GetFlushDataResponse) GetNodesStateRoot() string {
	if m != nil {
		return m.NodesStateRoot
	}
	return ""
}

func (m *GetFlushDataResponse) GetResult() *ResultCode {
	if m != nil {
		return m.Result
	}
	return nil
}

//*
// @dev Array of 4 FE
// @param {fe0} - Field Element value for pos 0
// @param {fe1} - Field Element value for pos 1
// @param {fe2} - Field Element value for pos 2
// @param {fe3} - Field Element value for pos 3
type Fea struct {
	Fe0                  uint64   `protobuf:"varint,1,opt,name=fe0,proto3" json:"fe0,omitempty"`
	Fe1                  uint64   `protobuf:"varint,2,opt,name=fe1,proto3" json:"fe1,omitempty"`
	Fe2                  uint64   `protobuf:"varint,3,opt,name=fe2,proto3" json:"fe2,omitempty"`
	Fe3                  uint64   `protobuf:"varint,4,opt,name=fe3,proto3" json:"fe3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fea) Reset()         { *m = Fea{} }
func (m *Fea) String() string { return proto.CompactTextString(m) }
func (*Fea) ProtoMessage()    {}
func (*Fea) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{15}
}

func (m *Fea) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fea.Unmarshal(m, b)
}
func (m *Fea) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fea.Marshal(b, m, deterministic)
}
func (m *Fea) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fea.Merge(m, src)
}
func (m *Fea) XXX_Size() int {
	return xxx_messageInfo_Fea.Size(m)
}
func (m *Fea) XXX_DiscardUnknown() {
	xxx_messageInfo_Fea.DiscardUnknown(m)
}

var xxx_messageInfo_Fea proto.InternalMessageInfo

func (m *Fea) GetFe0() uint64 {
	if m != nil {
		return m.Fe0
	}
	return 0
}

func (m *Fea) GetFe1() uint64 {
	if m != nil {
		return m.Fe1
	}
	return 0
}

func (m *Fea) GetFe2() uint64 {
	if m != nil {
		return m.Fe2
	}
	return 0
}

func (m *Fea) GetFe3() uint64 {
	if m != nil {
		return m.Fe3
	}
	return 0
}

//*
// @dev FE (Field Element) List
// @param {fe} - list of Fe
type FeList struct {
	Fe                   []uint64 `protobuf:"varint,1,rep,packed,name=fe,proto3" json:"fe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeList) Reset()         { *m = FeList{} }
func (m *FeList) String() string { return proto.CompactTextString(m) }
func (*FeList) ProtoMessage()    {}
func (*FeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{16}
}

func (m *FeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeList.Unmarshal(m, b)
}
func (m *FeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeList.Marshal(b, m, deterministic)
}
func (m *FeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeList.Merge(m, src)
}
func (m *FeList) XXX_Size() int {
	return xxx_messageInfo_FeList.Size(m)
}
func (m *FeList) XXX_DiscardUnknown() {
	xxx_messageInfo_FeList.DiscardUnknown(m)
}

var xxx_messageInfo_FeList proto.InternalMessageInfo

func (m *FeList) GetFe() []uint64 {
	if m != nil {
		return m.Fe
	}
	return nil
}

//*
// @dev Siblings List
// @param {sibling} - list of siblings
type SiblingList struct {
	Sibling              []uint64 `protobuf:"varint,1,rep,packed,name=sibling,proto3" json:"sibling,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SiblingList) Reset()         { *m = SiblingList{} }
func (m *SiblingList) String() string { return proto.CompactTextString(m) }
func (*SiblingList) ProtoMessage()    {}
func (*SiblingList) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{17}
}

func (m *SiblingList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SiblingList.Unmarshal(m, b)
}
func (m *SiblingList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SiblingList.Marshal(b, m, deterministic)
}
func (m *SiblingList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SiblingList.Merge(m, src)
}
func (m *SiblingList) XXX_Size() int {
	return xxx_messageInfo_SiblingList.Size(m)
}
func (m *SiblingList) XXX_DiscardUnknown() {
	xxx_messageInfo_SiblingList.DiscardUnknown(m)
}

var xxx_messageInfo_SiblingList proto.InternalMessageInfo

func (m *SiblingList) GetSibling() []uint64 {
	if m != nil {
		return m.Sibling
	}
	return nil
}

//*
// @dev Flush Data
// @param {key} - hash key
// @param {value} - string value
type FlushData struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlushData) Reset()         { *m = FlushData{} }
func (m *FlushData) String() string { return proto.CompactTextString(m) }
func (*FlushData) ProtoMessage()    {}
func (*FlushData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{18}
}

func (m *FlushData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlushData.Unmarshal(m, b)
}
func (m *FlushData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlushData.Marshal(b, m, deterministic)
}
func (m *FlushData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlushData.Merge(m, src)
}
func (m *FlushData) XXX_Size() int {
	return xxx_messageInfo_FlushData.Size(m)
}
func (m *FlushData) XXX_DiscardUnknown() {
	xxx_messageInfo_FlushData.DiscardUnknown(m)
}

var xxx_messageInfo_FlushData proto.InternalMessageInfo

func (m *FlushData) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *FlushData) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

//*
// @dev Result code
// @param {code} - result code
type ResultCode struct {
	Code                 ResultCode_Code `protobuf:"varint,1,opt,name=code,proto3,enum=hashdb.v1.ResultCode_Code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResultCode) Reset()         { *m = ResultCode{} }
func (m *ResultCode) String() string { return proto.CompactTextString(m) }
func (*ResultCode) ProtoMessage()    {}
func (*ResultCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_9539c961f4d5f9a5, []int{19}
}

func (m *ResultCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultCode.Unmarshal(m, b)
}
func (m *ResultCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultCode.Marshal(b, m, deterministic)
}
func (m *ResultCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultCode.Merge(m, src)
}
func (m *ResultCode) XXX_Size() int {
	return xxx_messageInfo_ResultCode.Size(m)
}
func (m *ResultCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultCode.DiscardUnknown(m)
}

var xxx_messageInfo_ResultCode proto.InternalMessageInfo

func (m *ResultCode) GetCode() ResultCode_Code {
	if m != nil {
		return m.Code
	}
	return ResultCode_CODE_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("hashdb.v1.ResultCode_Code", ResultCode_Code_name, ResultCode_Code_value)
	proto.RegisterType((*Version)(nil), "hashdb.v1.Version")
	proto.RegisterType((*SetRequest)(nil), "hashdb.v1.SetRequest")
	proto.RegisterType((*GetRequest)(nil), "hashdb.v1.GetRequest")
	proto.RegisterType((*SetProgramRequest)(nil), "hashdb.v1.SetProgramRequest")
	proto.RegisterType((*GetProgramRequest)(nil), "hashdb.v1.GetProgramRequest")
	proto.RegisterType((*LoadDBRequest)(nil), "hashdb.v1.LoadDBRequest")
	proto.RegisterMapType((map[string]*FeList)(nil), "hashdb.v1.LoadDBRequest.InputDbEntry")
	proto.RegisterType((*LoadProgramDBRequest)(nil), "hashdb.v1.LoadProgramDBRequest")
	proto.RegisterMapType((map[string][]byte)(nil), "hashdb.v1.LoadProgramDBRequest.InputProgramDbEntry")
	proto.RegisterType((*GetFlushDataRequest)(nil), "hashdb.v1.GetFlushDataRequest")
	proto.RegisterType((*SetResponse)(nil), "hashdb.v1.SetResponse")
	proto.RegisterMapType((map[string]*FeList)(nil), "hashdb.v1.SetResponse.DbReadLogEntry")
	proto.RegisterMapType((map[uint64]*SiblingList)(nil), "hashdb.v1.SetResponse.SiblingsEntry")
	proto.RegisterType((*GetResponse)(nil), "hashdb.v1.GetResponse")
	proto.RegisterMapType((map[string]*FeList)(nil), "hashdb.v1.GetResponse.DbReadLogEntry")
	proto.RegisterMapType((map[uint64]*SiblingList)(nil), "hashdb.v1.GetResponse.SiblingsEntry")
	proto.RegisterType((*SetProgramResponse)(nil), "hashdb.v1.SetProgramResponse")
	proto.RegisterType((*GetProgramResponse)(nil), "hashdb.v1.GetProgramResponse")
	proto.RegisterType((*FlushResponse)(nil), "hashdb.v1.FlushResponse")
	proto.RegisterType((*GetFlushStatusResponse)(nil), "hashdb.v1.GetFlushStatusResponse")
	proto.RegisterType((*GetFlushDataResponse)(nil), "hashdb.v1.GetFlushDataResponse")
	proto.RegisterType((*Fea)(nil), "hashdb.v1.Fea")
	proto.RegisterType((*FeList)(nil), "hashdb.v1.FeList")
	proto.RegisterType((*SiblingList)(nil), "hashdb.v1.SiblingList")
	proto.RegisterType((*FlushData)(nil), "hashdb.v1.FlushData")
	proto.RegisterType((*ResultCode)(nil), "hashdb.v1.ResultCode")
}

func init() {
	proto.RegisterFile("hashdb.proto", fileDescriptor_9539c961f4d5f9a5)
}

var fileDescriptor_9539c961f4d5f9a5 = []byte{
	// 1495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0xdd, 0x72, 0xdb, 0xc4,
	0x17, 0x8f, 0x6c, 0xf9, 0xeb, 0xf8, 0xa3, 0xce, 0xe6, 0xa3, 0xaa, 0xf3, 0xff, 0xb7, 0x41, 0x50,
	0x92, 0x32, 0xad, 0xe3, 0x24, 0x40, 0x19, 0xca, 0x45, 0x93, 0xd8, 0x31, 0xa6, 0x89, 0x53, 0xe4,
	0xa4, 0x0c, 0x9d, 0x61, 0x34, 0x72, 0xb4, 0x76, 0x34, 0x55, 0xb4, 0x46, 0x5a, 0xa7, 0xe4, 0x12,
	0x5e, 0x81, 0xe1, 0x75, 0x18, 0x1e, 0x81, 0x8b, 0x5e, 0xf0, 0x06, 0x0c, 0x6f, 0xc1, 0xec, 0xae,
	0x64, 0x4b, 0x8e, 0x9c, 0x38, 0x03, 0x57, 0xdc, 0x69, 0xcf, 0xf9, 0x9d, 0xb3, 0xe7, 0x1c, 0xff,
	0xf6, 0x9c, 0x5d, 0x43, 0xe1, 0xcc, 0xf0, 0xce, 0xcc, 0x6e, 0x75, 0xe0, 0x12, 0x4a, 0x50, 0xce,
	0x5f, 0x5d, 0x6c, 0x56, 0x56, 0xfa, 0x84, 0xf4, 0x6d, 0xbc, 0xc1, 0x15, 0xdd, 0x61, 0x6f, 0x03,
	0x9f, 0x0f, 0xe8, 0xa5, 0xc0, 0xa9, 0x0f, 0x20, 0xf3, 0x0a, 0xbb, 0x9e, 0x45, 0x1c, 0xb4, 0x08,
	0xe9, 0x8b, 0x9a, 0x5e, 0xd3, 0x37, 0x15, 0x69, 0x55, 0x5a, 0xcf, 0x69, 0xf2, 0x45, 0xad, 0xb6,
	0xa9, 0xfe, 0x2e, 0x01, 0x74, 0x30, 0xd5, 0xf0, 0xf7, 0x43, 0xec, 0x51, 0xf4, 0x08, 0xb2, 0xc4,
	0x36, 0x75, 0x97, 0x10, 0xca, 0x61, 0xf9, 0xad, 0x52, 0x75, 0xb4, 0x55, 0x75, 0x1f, 0x1b, 0x5a,
	0x86, 0xd8, 0xa6, 0x46, 0x08, 0x45, 0xab, 0x90, 0x7c, 0x83, 0x2f, 0x95, 0x44, 0x2c, 0x8a, 0xa9,
	0xd0, 0x22, 0xa4, 0x2e, 0x0c, 0x7b, 0x88, 0x95, 0x24, 0xdf, 0x50, 0x2c, 0xd0, 0x7d, 0x80, 0x01,
	0x0b, 0xc9, 0xa3, 0xd8, 0xa1, 0x8a, 0xbc, 0x2a, 0xad, 0x67, 0xb5, 0x90, 0x04, 0x29, 0x90, 0x31,
	0x31, 0x35, 0x2c, 0xdb, 0x53, 0x52, 0x5c, 0x19, 0x2c, 0xd1, 0x43, 0xb8, 0xd3, 0xc7, 0x54, 0x37,
	0xbb, 0xba, 0x8b, 0x0d, 0x53, 0xb7, 0x49, 0x5f, 0x49, 0x73, 0x44, 0xa1, 0x8f, 0x69, 0xbd, 0xab,
	0x61, 0xc3, 0x3c, 0x20, 0x7d, 0xf5, 0x67, 0x09, 0xa0, 0x39, 0x4e, 0x49, 0x05, 0xf9, 0x9a, 0x74,
	0xb8, 0x6e, 0x86, 0x5c, 0x42, 0x51, 0x25, 0x6f, 0x8c, 0x4a, 0x8e, 0x89, 0xca, 0x82, 0xf9, 0x0e,
	0xa6, 0x2f, 0x5d, 0xd2, 0x77, 0x8d, 0xf3, 0x20, 0x36, 0x7f, 0x5f, 0x69, 0xfa, 0xbe, 0x08, 0x64,
	0xd3, 0xa0, 0x06, 0x0f, 0xad, 0xa0, 0xf1, 0xef, 0x89, 0x0a, 0x26, 0x27, 0x2b, 0xa8, 0x7e, 0x02,
	0xf3, 0xcd, 0xdb, 0x6f, 0xa5, 0xfe, 0x26, 0x41, 0xf1, 0x80, 0x18, 0x66, 0x7d, 0x37, 0xb0, 0x79,
	0x0e, 0x59, 0xcb, 0x19, 0x0c, 0x59, 0x72, 0x8a, 0xb4, 0x9a, 0x5c, 0xcf, 0x6f, 0x3d, 0x0c, 0x19,
	0x46, 0xb0, 0xd5, 0x16, 0x03, 0xd6, 0xbb, 0x0d, 0x87, 0xba, 0x97, 0x5a, 0xc6, 0x12, 0xab, 0x89,
	0x50, 0x13, 0x93, 0xa1, 0x56, 0x0e, 0xa1, 0x10, 0x36, 0x44, 0xe5, 0x71, 0x94, 0x39, 0x51, 0x80,
	0xb5, 0x80, 0x44, 0xe2, 0xc7, 0x99, 0x8f, 0x44, 0x7e, 0x60, 0x79, 0xd4, 0xe7, 0xd5, 0xe7, 0x89,
	0xcf, 0x24, 0xf5, 0x0f, 0x09, 0x16, 0x59, 0x58, 0x7e, 0xee, 0xe3, 0x4c, 0xbe, 0x83, 0xb2, 0xc8,
	0x64, 0x20, 0x34, 0xe3, 0x8c, 0xb6, 0x27, 0x32, 0x9a, 0x34, 0x15, 0x89, 0x05, 0x52, 0x3f, 0xbf,
	0x92, 0x15, 0x11, 0xde, 0x98, 0xe6, 0x0e, 0x2c, 0xc4, 0xb8, 0x89, 0xc9, 0x76, 0x31, 0x9c, 0x6d,
	0x21, 0x9c, 0x5a, 0x0d, 0x16, 0x9a, 0x98, 0xee, 0xdb, 0x43, 0xef, 0xac, 0x6e, 0x50, 0x23, 0x48,
	0xec, 0x1e, 0x64, 0x7b, 0x4c, 0xa6, 0x5b, 0x26, 0xf7, 0x23, 0x6b, 0x19, 0xbe, 0x6e, 0x99, 0xea,
	0xaf, 0x29, 0xc8, 0xf3, 0xa3, 0xed, 0x0d, 0x88, 0xe3, 0xe1, 0xdb, 0x9c, 0xed, 0x47, 0x90, 0x75,
	0xf0, 0x5b, 0x01, 0x8d, 0x3f, 0x14, 0x19, 0x07, 0xbf, 0x0d, 0xb7, 0x81, 0xe4, 0x74, 0x0a, 0x3f,
	0x87, 0xac, 0x67, 0x75, 0x6d, 0xcb, 0xe9, 0x7b, 0x8a, 0xcc, 0x6b, 0xfe, 0x41, 0x08, 0x16, 0x8a,
	0xb0, 0xda, 0xf1, 0x61, 0xa2, 0xc8, 0x23, 0x2b, 0xb4, 0x06, 0x19, 0xcb, 0xf1, 0x74, 0xb6, 0x4f,
	0x2a, 0x76, 0x9f, 0xb4, 0xe5, 0x78, 0x2f, 0xf0, 0x25, 0x5a, 0x81, 0x1c, 0x03, 0x8a, 0x12, 0xa6,
	0x79, 0x59, 0xb3, 0x96, 0xe3, 0xbd, 0xe2, 0x8d, 0xe7, 0x2e, 0x64, 0x2c, 0x4f, 0x27, 0xb6, 0x59,
	0x53, 0x32, 0xfc, 0x17, 0x4a, 0x5b, 0xde, 0x91, 0x6d, 0xd6, 0x98, 0x15, 0x2b, 0x8c, 0xb0, 0xca,
	0x0a, 0x2b, 0x62, 0x9b, 0xc2, 0x6a, 0x05, 0x72, 0xac, 0x14, 0x42, 0x99, 0x13, 0x4a, 0x07, 0xbf,
	0x15, 0x4a, 0x04, 0xf2, 0x39, 0x31, 0xb1, 0x02, 0xa2, 0xa3, 0xb2, 0x6f, 0xf4, 0x18, 0xd0, 0xc0,
	0x25, 0xa4, 0xa7, 0xb3, 0x10, 0xf5, 0x53, 0x32, 0x74, 0x28, 0x76, 0x95, 0x3c, 0xff, 0x6d, 0xca,
	0x5c, 0xf3, 0xa5, 0xe1, 0x9d, 0xed, 0x09, 0x39, 0x6a, 0x40, 0x3e, 0xdc, 0x39, 0x0a, 0x57, 0x4e,
	0x59, 0xb8, 0x3e, 0xa3, 0x6e, 0x22, 0x0a, 0x94, 0x33, 0x83, 0x35, 0x7a, 0x02, 0x69, 0x17, 0x7b,
	0x43, 0x9b, 0x2a, 0x45, 0x5e, 0xa0, 0xa5, 0x90, 0x07, 0x8d, 0x2b, 0xf6, 0x88, 0x89, 0x35, 0x1f,
	0x54, 0xe9, 0x40, 0x31, 0x52, 0xeb, 0x30, 0x13, 0x65, 0xf1, 0xab, 0x3d, 0x8e, 0x9e, 0xbb, 0xe5,
	0x70, 0x48, 0xc2, 0x74, 0xe2, 0xf0, 0x55, 0x8e, 0xa0, 0x14, 0x0d, 0xf0, 0x9f, 0x9e, 0xe6, 0x77,
	0x32, 0xe4, 0x9b, 0x21, 0x02, 0xff, 0x3b, 0x9d, 0x3c, 0x4c, 0xc7, 0xe4, 0x15, 0x3a, 0x36, 0x6f,
	0x47, 0x47, 0x79, 0x76, 0x3a, 0xa6, 0xa6, 0xd3, 0x31, 0x1d, 0xa1, 0xe3, 0xa8, 0x07, 0x64, 0xc2,
	0x63, 0x33, 0x9e, 0x56, 0xd9, 0xd9, 0x68, 0x95, 0xbb, 0x42, 0xab, 0xe6, 0x2d, 0x69, 0x05, 0xff,
	0x1d, 0x5a, 0xed, 0x01, 0x0a, 0x4f, 0x62, 0x9f, 0x5c, 0xe3, 0x54, 0xa5, 0x19, 0x52, 0x55, 0xbf,
	0x01, 0xd4, 0xbc, 0xea, 0x24, 0x98, 0xd6, 0x52, 0x68, 0x5a, 0x8f, 0x1d, 0x27, 0x66, 0x71, 0xfc,
	0xa3, 0x04, 0x45, 0xde, 0xe5, 0x47, 0x4e, 0xa7, 0xb7, 0x78, 0xf4, 0x21, 0xdc, 0xf1, 0x28, 0x71,
	0xb1, 0xa9, 0x8f, 0x10, 0x09, 0x8e, 0x28, 0x0a, 0xf1, 0xbe, 0x8f, 0x1b, 0xc7, 0x90, 0x9c, 0x25,
	0x86, 0x3f, 0x13, 0xb0, 0x1c, 0x0c, 0x9b, 0x0e, 0x35, 0xe8, 0xd0, 0x1b, 0x05, 0x13, 0xb3, 0xa3,
	0x14, 0xb7, 0xe3, 0x3a, 0x94, 0x99, 0xc0, 0x72, 0xfa, 0x93, 0xa1, 0x95, 0x7c, 0x79, 0x80, 0x54,
	0xa1, 0x68, 0x1b, 0x1e, 0x1d, 0xc3, 0x92, 0x1c, 0x96, 0x67, 0xc2, 0x00, 0xb3, 0x0d, 0xcb, 0x03,
	0xec, 0x98, 0xcc, 0x1b, 0x25, 0x3e, 0xd2, 0x21, 0x26, 0xf6, 0xf8, 0x01, 0x94, 0xb5, 0x05, 0x5f,
	0x7b, 0x4c, 0xb8, 0x45, 0x9b, 0xa9, 0xd0, 0x53, 0x50, 0xae, 0x18, 0xf9, 0xe3, 0x9f, 0x1f, 0x46,
	0x59, 0x5b, 0x8a, 0x9a, 0xf9, 0xbf, 0x26, 0x7a, 0x1f, 0x8a, 0x41, 0xec, 0x62, 0x93, 0x34, 0x47,
	0x17, 0x7c, 0xa1, 0xf0, 0xbe, 0x26, 0x0a, 0xc1, 0x40, 0x81, 0xd3, 0x4c, 0x24, 0xbf, 0xc0, 0xdb,
	0x0a, 0xe4, 0x06, 0x2e, 0xb9, 0xc0, 0x2e, 0xcb, 0xcd, 0x9f, 0x2e, 0x42, 0xd0, 0x32, 0xd5, 0xbf,
	0x12, 0xb0, 0x18, 0x1d, 0xeb, 0xb7, 0xac, 0xf3, 0x47, 0x90, 0x12, 0x31, 0x26, 0xf8, 0x11, 0x5f,
	0x0c, 0x33, 0x7f, 0xe4, 0x54, 0x40, 0xd0, 0x53, 0x28, 0xf0, 0x0f, 0x7d, 0x38, 0x30, 0x0d, 0x8a,
	0xfd, 0xee, 0x17, 0x6f, 0x92, 0xe7, 0xc8, 0x13, 0x0e, 0x44, 0x55, 0xc8, 0x04, 0x39, 0xca, 0xd7,
	0xd8, 0x04, 0x20, 0xf4, 0x0c, 0x4a, 0xc1, 0x3d, 0xcb, 0xdf, 0x2a, 0x75, 0x8d, 0x59, 0xd1, 0xc7,
	0xfa, 0x9b, 0xad, 0x43, 0x59, 0x44, 0xe9, 0x51, 0x83, 0x62, 0x71, 0x07, 0x11, 0xa3, 0xbc, 0xc4,
	0xe5, 0x8c, 0x90, 0x98, 0x5f, 0x3d, 0xc6, 0xac, 0xce, 0xcc, 0xc2, 0xea, 0x43, 0x48, 0xee, 0x63,
	0x83, 0x75, 0x8f, 0x1e, 0xae, 0x05, 0x3d, 0xa9, 0x87, 0x6b, 0x42, 0xb2, 0xe9, 0xd3, 0x93, 0x7d,
	0x0a, 0xc9, 0x96, 0xcf, 0x44, 0xf6, 0x29, 0x24, 0xdb, 0x3e, 0xdd, 0xd8, 0xa7, 0xaa, 0x40, 0x5a,
	0xf4, 0x16, 0x54, 0x82, 0x44, 0x0f, 0xf3, 0xeb, 0xa4, 0xac, 0x25, 0x7a, 0x58, 0x5d, 0x83, 0x7c,
	0xa8, 0x97, 0xb1, 0xa7, 0x83, 0x3f, 0x3a, 0x7c, 0x4c, 0xb0, 0x54, 0xb7, 0x21, 0x37, 0x2a, 0xc3,
	0x4d, 0x97, 0xc1, 0x60, 0x10, 0xa8, 0xef, 0x24, 0x80, 0x71, 0x76, 0xa8, 0x0a, 0xf2, 0x29, 0xbb,
	0x82, 0x30, 0xbb, 0xd2, 0x56, 0x25, 0xb6, 0x04, 0x55, 0x5e, 0x07, 0x8e, 0x53, 0x7f, 0x91, 0x40,
	0xe6, 0x86, 0x8b, 0x50, 0xde, 0x3b, 0xaa, 0x37, 0xf4, 0x93, 0x76, 0xe7, 0x65, 0x63, 0xaf, 0xb5,
	0xdf, 0x6a, 0xd4, 0xcb, 0x73, 0xa8, 0x0c, 0x05, 0x2e, 0xed, 0x9c, 0xec, 0xed, 0x35, 0x3a, 0x9d,
	0xb2, 0x84, 0xee, 0xc1, 0x12, 0x97, 0xd4, 0x77, 0xf5, 0x17, 0x8d, 0x6f, 0xf5, 0xf6, 0xd1, 0xb1,
	0xbe, 0x7f, 0x74, 0xd2, 0xae, 0x97, 0x13, 0x68, 0x1e, 0x8a, 0x81, 0xaa, 0xa1, 0x69, 0x47, 0x5a,
	0x39, 0x89, 0xee, 0xc2, 0x02, 0x17, 0xb5, 0xda, 0xc7, 0x0d, 0xad, 0xbd, 0x73, 0xe0, 0x2b, 0x64,
	0x74, 0x1f, 0x2a, 0xc2, 0xf1, 0xe1, 0xb1, 0xde, 0x6a, 0xbf, 0xda, 0x39, 0x68, 0xd5, 0xf5, 0xfa,
	0xce, 0xf1, 0x8e, 0xde, 0x69, 0xbd, 0x6e, 0x94, 0x4b, 0x5b, 0x3f, 0xa5, 0xa0, 0xc8, 0x26, 0x58,
	0x7d, 0xb7, 0x83, 0xdd, 0x0b, 0xeb, 0x14, 0xa3, 0x4f, 0x21, 0xd9, 0xc1, 0x14, 0x2d, 0x4d, 0x5e,
	0x86, 0xf8, 0xc5, 0xb7, 0xb2, 0x1c, 0x7f, 0x47, 0x52, 0xe7, 0x98, 0x5d, 0x73, 0xc2, 0xae, 0x19,
	0x6f, 0xd7, 0x8c, 0xd8, 0xbd, 0xe0, 0x2f, 0xe1, 0xe0, 0xd8, 0xfe, 0x2f, 0xea, 0x3f, 0xfa, 0x9a,
	0xaa, 0xfc, 0x7f, 0x8a, 0x36, 0xec, 0xac, 0x19, 0xef, 0xac, 0x79, 0xad, 0xb3, 0x66, 0x9c, 0xb3,
	0x2f, 0x20, 0x2d, 0x1e, 0x5b, 0x48, 0x99, 0xf6, 0xfe, 0xaa, 0x2c, 0x57, 0xc5, 0xff, 0x00, 0xd5,
	0xe0, 0x7f, 0x80, 0x6a, 0xe3, 0x7c, 0x40, 0x2f, 0xd5, 0x39, 0xf4, 0x95, 0x78, 0xd6, 0x8d, 0x1e,
	0x36, 0xe8, 0xc1, 0x0d, 0x4f, 0x9e, 0x6b, 0x7c, 0x3d, 0x83, 0x14, 0x67, 0x2c, 0x9a, 0x02, 0xa9,
	0x28, 0x93, 0x47, 0x3c, 0x94, 0xc6, 0x21, 0x94, 0xa2, 0x53, 0x65, 0xaa, 0x97, 0xf7, 0xa2, 0x15,
	0x89, 0x19, 0x44, 0xea, 0x1c, 0xfa, 0x1a, 0x0a, 0xe1, 0xd6, 0x89, 0xee, 0xc7, 0x18, 0x85, 0x9e,
	0x4a, 0x95, 0x07, 0x53, 0xf5, 0x81, 0xcb, 0xdd, 0x8f, 0x5f, 0x6f, 0xf5, 0x2d, 0x7a, 0x36, 0xec,
	0x56, 0x4f, 0xc9, 0xf9, 0x46, 0xed, 0x87, 0x97, 0xc4, 0xbe, 0xec, 0x13, 0x67, 0xc3, 0x1b, 0x0e,
	0xb0, 0xeb, 0x60, 0xea, 0x6d, 0x3d, 0x61, 0x3d, 0x68, 0xe3, 0x1c, 0xbb, 0x6f, 0x6c, 0x4c, 0x5d,
	0x8c, 0x37, 0x06, 0xdd, 0x6e, 0x9a, 0x47, 0xbf, 0xfd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x28,
	0x77, 0x59, 0xf6, 0xa3, 0x11, 0x00, 0x00,
}
